# Generated by Django 4.1.4 on 2022-12-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_perks'),
    ]

    operations = [
        migrations.AddField(
            model_name='perk',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='perk',
            name='details',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
